acs-aem-samples/index.html

Small typo discovered on samples page.

Fix typo in samples index.

---

acs-aem-samples/index.html

Changed the touch ui header link, It was pointing to workflow

Touch UI section head link point to touch-ui

---

_posts/acs-aem-commons/features/2015-05-19-wcm-views.md

Fix typo in 2015-05-19-wcm-views.md

---

_posts/acs-aem-commons/features/2015-08-21-version-comparison.md

Requires Sling Models in v1.1.0 at minimum

Added version notes

---

_posts/acs-aem-commons/features/2015-10-01-jcr-checksum-compare.md

The checksum part has been removed.

Fixed invalid reference to JCR compare page

---

_posts/acs-aem-commons/features/2015-10-01-jcr-checksum-compare.md

"difficult to fine" -> "difficult to find"

Fix typo that has been driving me nuts

---

_posts/acs-aem-commons/features/2015-10-02-ensure-oak-index.md

Prevent confusion about forceRefresh vs. forceReindex

Fixing forceReindex example

---

_posts/acs-aem-commons/features/2013-06-20-delegating-servlet.md

Corrected the file name for OSGi configuration of an instance of the Delegating Servlet service.

Corrected an error in Delegating Servlet documentation.

---

_posts/acs-aem-commons/features/2013-08-01-widgets.md

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/871/files

Add documentation for new Multi Field Panel helper

---

_posts/acs-aem-commons/news/2016-12-21-announce-release-3.6.0.txt

Simple doc update to mention new feature added in 2.9.0

Update description for 2.9.0 to include Shared Component Properties

---

_announcements/acs-aem-commons/3-9-0.txt

per https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/991

Updated 3.9.0 release to call out the update for Shared Component Props

---

_acs-aem-commons/features/workflow-processes/set-replication-status/index.md

Made some minor edits for clarity of content and fixed the replicationAction options to match those available in the ReplicationStatusManager.

Updates to the Set Replication Status feature doc.

---

_acs-aem-commons/features/workflow-processes/workflow-delegation/index.md

The current description is too specific

update documentation for workflow delegation step

---

_acs-aem-commons/features/sitemap/index.md

updated sitemap documentation for extensionless urls, demonstrating usage and description.

updated sitemap documentation for extensionless urls

---

_acs-aem-commons/features/package-replication-status-updater/index.md

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1411

describe changes from

---

_acs-aem-commons/features/version-compare/index.md

whether the.... ended the sentence on line 24. I assumed the intended completion, and applied it in this edit.

Finish a sentence describing visual representation

---

_acs-aem-commons/features/dispatcher-flush-ui/index.md

Corrected minor typo

---

_acs-aem-commons/features/http-cache/index.md

In memory storage is lost on application stop.

Finished thought on in-mem storage

---

_acs-aem-commons/features/package-replication-status-updater/index.md

Minor typo correction

---

_data/acs-aem-commons.yml

Branch for 4.0.0 we can do PR to for updates

Updated  ACS aem commons version to 4.0.0

---

acs-aem-samples/index.html

Reference to the layout-wcm-pages project

Added the reference to layout-wcm-pages

---

_acs-aem-commons/features/http-cache/subpages/invalidation.md

I made some mistakes / misunderstood something about the invalidation and this correct the mistake.

Corrected mistakes regarding invalidation in the HTTP cache invalidation

---

_acs-aem-commons/features/sling-model-injectors/hierarchical-page-property/index.md

Fix example code

---

_acs-aem-tools/features/clientlibs-optimizer/index.md

add some explanation around embeds/dependencies including limitations of transitive embeds

improve documentation around Client Library optimizer

---

acs-aem-commons/pages/maven.md

added docs for the filevault package plugin

---

_acs-aem-commons/features/parsys-limiter/index.md

Remark for [1830](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1830).

Add embed vs depepndency remark for Parsys Limiter

---

_acs-aem-commons/features/ui-widgets/icon-picker/index.md

Link to github page returned 404, updated it to the correct page

Update link to Wrapper Client Library

---

_acs-aem-commons/features/deprecated/coral-angular/index.md

Yes this page is deprecated, no that doesn't mean typos won't confuse people.

Trivial typo change to coral-angular page

---

_includes/shared/footer.html

I think this is the only reference to the old corporate name.
h/t James Lockman

Update corporate name

---

_acs-aem-commons/features/on-deploy-scripts/index.md

Discussed on https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2324

adding aemcs-incompatible tag

---

_acs-aem-commons/features/ensure-service-users/index.md

Fix sample config for EnsureServiceUser

---

_acs-aem-commons/features/redirect-manager/subpages/mappings.md

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3102

update config example to be inline with implementation

---

_acs-aem-commons/features/workflow-processes/content-traversing-replicate-with-options/index.md

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3166

Updated for ACS Commons Issue #3166

---

acs-aem-commons/pages/maven.md

List AEMaaCS first, still leverage subpackage for AEM6.5

Clarify differences between AEMaaCS and AEM 6.5 for embedding

---

_acs-aem-commons/features/contentsync/index.md

update the docs as requested in https://github.com/Adobe-Consulting-Services/acs-aem-commons/discussions/3449

Content Sync is not compatible with IP Whitelist index.md
