acs-aem-commons/pages/maven.md

Step 2 was missing, so I have shifted 3 and 4 up.
Code blocks on the [site](http://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html) were incorrectly indented.  It seems the MD parser was trimming the first line of the blocks.  Reduced the indent in each block to compensate for this.  Another option may be to instead use
```xml
<fenced>code</fenced>
```

Update maven.md to correct numbering and indents

---

_posts/acs-aem-commons/features/2013-09-30-errorpagehandler.md

Added a section to the Error Page Handler to describe how one may add the necessary configuration for I18NFilter, when the I18N bundle is required by the error pages.

Expand Error Page Handler documentation for I18N

---

_posts/acs-aem-commons/features/2013-09-30-errorpagehandler.md

the DispatcherPassError should be set to '0' if we want the Dispatcher/AEM to handle the error, if its '1' then apache handles it.
BTW LOVE LOVE this feature. So easy to integrate into projects :+1:

updated documentation per dispatcher documentation

---

_includes/shared/youtube-player.html

@davidjgonzalez  Currently when the page is served through https, there are security errors (mixed content) and the video is not served.  Not sure how to test this though :-/

Make youtube video url protocol relative

---

_includes/acs-aem-tools/jumbotron.html
_includes/acs-aem-tools/slides/intro.html
acs-aem-tools/index.html

currently the ACS AEM tools site links directly to the "full" version of the AEM package, hiding the fact that a "min" version without external dependencies is available as well.
similar to the download link for ACS commons the ACS tools site should link to the github releases page offering both download links.

ACS AEM Tools Site: Reference github releases

---

_posts/acs-aem-commons/features/2014-01-01-simple-sitemap.md

Updated documentation of Site Map Servlet to include new properties for configuring DAM Assets to include in the sitemap.
Corresponds with pending PR https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/619

Updated documentation of Site Map Servlet

---

_posts/acs-aem-commons/features/2013-08-20-wcmmode-tags.md

Updated documentation of <wcmmode> tags to include a note on how to have the tags work correctly as an author switches between Edit and Preview modes.

How to get <wcmmode> tags to work when switching Edit/Preview

---

.gitignore
_posts/acs-aem-commons/features/2015-12-04-dispatcher-ttl.md

Updating documentation for Dispatcher TTL needing the Dispatcher Server-Agent HTTP Header. 
See [ACS Commons issue #798](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/798)

Cache Control Header

---

_acs-aem-commons/features/dispatcher-ttl/index.md

just links to the anchor name rather than giving the full path
The note link on the https://adobe-consulting-services.github.io/acs-aem-commons/features/dispatcher-ttl/index.html page currently links to https://adobe-consulting-services.github.io/acs-aem-commons/features/dispatcher-ttl/acs-aem-commons/features/dispatcher-ttl.html#note which gives a 404

Fixed broken note link in dispatcher-ttl docs

---

_acs-aem-commons/features/shared-component-properties/index.md

com.adobe.acs.commons.wcm.impl.PageRootProviderImpl into
com.adobe.acs.commons.wcm.impl.PageRootProviderConfig

Use real config class name in Shared Component Properties

---

_data/acs-aem-commons.yml

Fixes a few broken links on the documentation site where the baseurl is used without a trailing slash, so the base url is added to the page context.  
For example, the link to the versioned clientlib page on:
https://adobe-consulting-services.github.io/acs-aem-commons/features/utils-and-apis/static-reference-rewriter/index.html
...contains the `acs-aem-commons` part twice as it is added on after the `static-reference-rewriter` section like so:
https://adobe-consulting-services.github.io/acs-aem-commons/features/utils-and-apis/static-reference-rewriter/acs-aem-commons/features/versioned-clientlibs.html
there's also a few broken images at the locations here:
https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/search?l=Markdown&q=site.data.acs-aem-commons.baseurl …

Added leading slash to set baseurl context to the root.

---

_acs-aem-commons/features/bulk-workflow-manager/index.md
_acs-aem-commons/features/ensure-oak-index/index.md
_acs-aem-commons/features/file-fetcher/index.md
_acs-aem-commons/features/healthchecks/index.md
_acs-aem-commons/features/healthchecks/smtp/index.md
_acs-aem-commons/features/healthchecks/status-emailer/index.md
_acs-aem-commons/features/json-event-logger/index.md
_acs-aem-commons/features/mcp-tools/asset-ingestion/asset-ingestor/index.md
_acs-aem-commons/features/mcp-tools/asset-ingestion/index.md
_acs-aem-commons/features/mcp-tools/asset-ingestion/s3-asset-ingestor/index.md
_acs-aem-commons/features/mcp-tools/asset-ingestion/url-asset-ingestor/index.md
_acs-aem-commons/features/mcp-tools/refresh-folder-thumbnails/index.md
_acs-aem-commons/features/redirect-map-manager/index.md
_acs-aem-commons/features/remote-assets/index.md
_acs-aem-commons/features/versioned-clientlibs/index.md
_acs-aem-commons/features/workflow-processes/assets-rendition-matter/index.md
_acs-aem-commons/features/workflow-processes/assets-watermark-process/index.md
_acs-aem-commons/features/workflow-processes/brand-portal/index.md
_includes/acs-aem-commons/aemcs-incompatible.html
_layouts/acs-aem-commons_feature.html
_sass/_feature-docs.scss

Adds a banner to the feature docs for ACS Commons if frontmatter has
`tags: aemcs-incompatible`
Took a first pass at tagging obvious candidates.

Aem as a Cloud Service incompatibility banner

---

_acs-aem-commons/features/sitemap/index.md

Relatively straightforward change.  In the OSIG config example, the value for extensionless urls is incorrect and won't work.  Just fixing that to make it easier to use.

Extensionless URLs Format Fix

---

_acs-aem-commons/features/workflow-processes/assets-rendition-matter/index.md

The wf process index page link to the rendition matter process, and the page for that process, are both broken
https://adobe-consulting-services.github.io/acs-aem-commons/features/workflow-processes/index.html
https://adobe-consulting-services.github.io/acs-aem-commons/features/workflow-processes/assets-rendition-matter/index.html
For whatever reason, at least for me, they seem to render fine with Jekyll locally. Either way, it looks like there was just an extra `-` on the end front-matter delimiter. I've removed that to try to correct it.

fixing frontmatter delimiter for WF Process Doc Pages

---

_config.yml
_includes/acs-aem-projects/nav.html
_includes/shared/who-we-are.html
index.html

There have been numerous instances of folks misunderstanding Adobe Consulting Services' involvement in/ownership of the ACS AEM Commons project. 
The genesis of the project did primarily see contributions from Adobe Consulting Services however as the project has evolved, the bulk of activity and contributions are from non-Adobe Consulting Services people. 
To help alleviate confusion, what do we think about a "technical" rebranding to Adobe Community Sofware - we can keep the ACS acronym, but separate from the Adobe Consulting Services brand.
Ideally we'd also change the Github repo name, and also any mentions in the code base (pom.xml, readmes)

ACS -> AEM Community Software

---

_acs-aem-commons/features/redirect-manager/advanced.md
_acs-aem-commons/features/redirect-manager/index.md
_acs-aem-commons/features/redirect-manager/manage.md
_acs-aem-commons/features/redirect-manager/mappings.md

a few links were ending with .md which resulted in a 404. The PR changes these to .html.

fix broken links and typos in redirect manager docs

---

_data/acs-aem-commons.yml
acs-aem-commons/index.html
acs-aem-commons/pages/maven.md

Refer to compatibility chart for legacy AEM versions.
Remove workaround for https://issues.apache.org/jira/browse/JCRVLT-343
This closes #226

Always use the container-package `acs-aem-commons-content` for embedding

---

_acs-aem-commons/features/http-cache/subpages/invalidation.md

1. There is an HTTP Cache feature in the ACS AEM Commons Library (https://adobe-consulting-services.github.io/acs-aem-commons/features/http-cache/index.html).
2. HTTP Cache feature provides a configurable `JCRNodeChangeEventHandler` OSGi component.
3. Fully-qualified class name (FQCN) of `JCRNodeChangeEventHandler` is `com.adobe.acs.commons.httpcache.invalidator.event.JCRNodeChangeEventHandler` (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/httpcache/invalidator/event/JCRNodeChangeEventHandler.java). Therefore, OSGi configuration for the component should have in its name the mentioned FQCN incorporated.
4. According to the current documentation being changed within this pull request, OSGi configuration for …

docs: Fix JCRNodeChangeEventHandler config path

---

_acs-aem-commons/features/named-image-transform/index.md

mention processing profiles to generate renditions upfront instead on-the-fly

#3096 update docs of NamedImageTransform

---

_acs-aem-commons/features/report-builder/index.md

The existing link to the report landing page does not work. However, it works if adding `/content` to the URL.

Correct link to Report Landing Page

---

_acs-aem-commons/features/redirect-manager/index.md
_acs-aem-commons/features/redirect-map-manager/index.md

* Marking [Redirect Map Manager](https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html) as enabled in AEM CS as in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3420 should be in [next release 6.6.5](https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases)
* Separating [description of Apache HTTPD side](https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html#configuring-apache) into on-prem/AMS (previous version) and AEM CS version pointing currently to [Early Adopter program description](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/release-notes/2024/release-notes-2024-5-0#apache-rewritemaps-early-adopter)
cc: …

mark Redirect Map Manager as enabled in AEM CS

---

_acs-aem-commons/features/redirect-map-manager/index.md

Linking documentation on [Redirect Map Manager](https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html) usage in AEM as a Cloud Service - [Pipeline-free URL Redirects](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/content-delivery/pipeline-free-url-redirects) - available since [AEM CS Release 18311](https://experienceleague.adobe.com/en/docs/experience-manager-release-information/aem-release-updates/update-releases-roadmap?lang=en#aem-as-cloud-service)
cc: @davidjgonzalez @joerghoh @SachinMali

linking AEM CS docs on Redirect Map Manager usage

---

_acs-aem-commons/features/redirect-map-manager/index.md

Updating link in documentation on [Redirect Map Manager](https://adobe-consulting-services.github.io/acs-aem-commons/features/redirect-map-manager/index.html) availability in AEM as a Cloud Service to point to permanent [AEM CS Release 18311 page](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/maintenance/2024/2024-10-0?lang=en#18311)
cc: @davidjgonzalez @joerghoh @SachinMali

updating linked AEM CS docs page with permanent one for release 18311 for Redirect Map Manager usage

---

_acs-aem-commons/features/redirect-map-manager/index.md

Adding missed explicit minimal version from which Rewrite Map Manager works on AEM CS as well

added note on AEM CS availability since version 6.7.0 of ACS Commons
